Repository ait-aecid/logdata-anomaly-miner, pull requests merged in 2020-12, with the labels that each got.

#346 added Jenkinsfile
  Jenkinsfile
  aecid-testsuite/runSuspendModeTest.sh
Labels: test

#348 fixed errors with testing-dockerfile and paralell jenkins-builds
  Jenkinsfile
  aecid-testsuite/Dockerfile
Labels: test

#349 Jenkins: parallel-tests for demo-tests
  Jenkinsfile
Labels: test

#351 Fixes Issue #350
  README.md
Labels: documentation

#365 VTD_check_num_with_ETD
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py
Labels: enhancement

#368 Install: use specific branch for aminer-ansible
  scripts/aminer_install.sh
Labels: enhancement

#370 VTD warning if parameters have to be changed in the ETD
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableCorrelationDetector.py
Labels: enhancement

#371 Deb dockerfiles
  Jenkinsfile
  aecid-testsuite/docker/Dockerfile_deb
  scripts/distritest.sh
Labels: test
