Repository ait-aecid/logdata-anomaly-miner, pull requests merged in 2021-04, with the labels that each got.

#579 VTD CM test
  aecid-testsuite/unit/AnalysisComponentsPerformanceTest.py
  aecid-testsuite/unit/analysis/VariableCorrelationDetectorTest.py
  aecid-testsuite/unit/analysis/VariableTypeDetectorTest.py
  aecid-testsuite/unit/data/vtd_data/beta1_data_test3
  aecid-testsuite/unit/data/vtd_data/beta1_data_test7
  aecid-testsuite/unit/data/vtd_data/beta2_data_test3
  aecid-testsuite/unit/data/vtd_data/beta2_data_test7
  aecid-testsuite/unit/data/vtd_data/beta3_data_test3
  aecid-testsuite/unit/data/vtd_data/beta3_data_test7
  aecid-testsuite/unit/data/vtd_data/beta4_data_test3
  aecid-testsuite/unit/data/vtd_data/beta4_data_test7
  aecid-testsuite/unit/data/vtd_data/beta5_data_test3
  aecid-testsuite/unit/data/vtd_data/beta5_data_test7
  aecid-testsuite/unit/data/vtd_data/nor_data_test3
  aecid-testsuite/unit/data/vtd_data/nor_data_test7
  aecid-testsuite/unit/data/vtd_data/uni_data_test3
  aecid-testsuite/unit/data/vtd_data/uni_data_test7
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/AnalysisNormalisationSchema.json
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.json
Labels: bug, enhancement

#614 aminer.py: resolved hardcoded username and gropname where user_id and…
  source/root/usr/lib/logdata-anomaly-miner/aminer.py
Labels: bug

#602 Add timeout param to ESD
  aecid-testsuite/unit/analysis/EventSequenceDetectorTest.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventSequenceDetector.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/AnalysisNormalisationSchema.yml
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
Labels: enhancement

#619 Feature pca detector
  aecid-testsuite/unit/analysis/PCADetectorTest.py
  aecid-testsuite/unit/config/YamlConfigTest.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/PCADetector.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/AnalysisNormalisationSchema.yml
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
Labels: enhancement

#634 PathValueTimeIntervalDetector
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/PathValueTimeIntervalDetector.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/AnalysisNormalisationSchema.yml
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
Labels: enhancement

#679 fixed error when POSIX ACLs do not exist.
  source/root/usr/lib/logdata-anomaly-miner/aminer.py
Labels: bug

#680 TSA Arima
  requirements.txt
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventTypeDetector.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/TSAArimaDetector.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/AnalysisNormalisationSchema.yml
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
Labels: enhancement

#694 Add TSA ACF-threshold
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/TSAArimaDetector.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/AnalysisNormalisationSchema.yml
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
Labels: enhancement

#693 TSA round time window
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/TSAArimaDetector.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/AnalysisNormalisationSchema.yml
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
Labels: enhancement

#691 VTD: Improved initalization message
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py
Labels: enhancement
