Repository ait-aecid/logdata-anomaly-miner, pull requests merged in 2021-05, with the labels that each got.

#689 Improved the sliding CM Test statistic and added critical values.
  aecid-testsuite/unit/data/vtd_data/beta1_data_test6
  aecid-testsuite/unit/data/vtd_data/beta2_data_test3
  aecid-testsuite/unit/data/vtd_data/beta3_data_test3
  aecid-testsuite/unit/data/vtd_data/beta4_data_test3
  aecid-testsuite/unit/data/vtd_data/beta4_data_test7
  aecid-testsuite/unit/data/vtd_data/beta5_data_test3
  aecid-testsuite/unit/data/vtd_data/uni_data_test7
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py
Labels: enhancement

#706 added command-line parameters to documentation
  .gitignore
  docs/CONFIGURATION.rst
Labels: documentation

#709 Development
  Jenkinsfile
Labels: test

#713 Updated README.md
  README.md
Labels: documentation

#716 Improved command line options for install script
  scripts/aminer_install.sh
Labels: enhancement
