Repository ait-aecid/logdata-anomaly-miner, pull requests merged in 2021-06, with the labels that each got.

#739 Docs histo
  docs/CONFIGURATION.rst
  requirements.txt
Labels: documentation

#748 Fixed handling of empty sets in JsonModelElement
  source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
Labels: bug

#758 Fix systemd script
  source/root/lib/systemd/system/aminer.service
  source/root/usr/lib/logdata-anomaly-miner/metadata.py
Labels: bug

#768 TSA: Added variables
  docs/CONFIGURATION.rst
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/TSAArimaDetector.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/AnalysisNormalisationSchema.yml
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
Labels: enhancement

#762 TSA: Fixed bug new ET
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/TSAArimaDetector.py
Labels: bug

#772 Feature valuerangedetector
  aecid-testsuite/unit/analysis/ValueRangeDetectorTest.py
  aecid-testsuite/unit/data/YamlConfigTest.py
  docs/CONFIGURATION.rst
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/ValueRangeDetector.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
Labels: enhancement

#773 Feature charset detector
  aecid-testsuite/unit/analysis/CharsetDetectorTest.py
  aecid-testsuite/unit/data/YamlConfigTest.py
  docs/CONFIGURATION.rst
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/CharsetDetector.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
Labels: enhancement
