Repository ait-aecid/logdata-anomaly-miner, pull requests merged in 2021-09, with the labels that each got.

#937 Feature add json pretty
  docs/CONFIGURATION.rst
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/events/JsonConverterHandler.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/EventHandlerNormalisationSchema.yml
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/EventHandlerValidationSchema.yml
Labels: enhancement

#943 Development
  Dockerfile
  aecid-testsuite/Dockerfile
Labels: bug

#954 Added config file for test-scripts and changed the kafka version to 2…
  aecid-testsuite/config
  aecid-testsuite/integration/aminerIntegrationTest2.sh
  aecid-testsuite/integration/declarations.sh
  aecid-testsuite/runCoverageTests.sh
  aecid-testsuite/runUnittests.sh
Labels: bug, test

#952 Feature supervisord
  Dockerfile
  aecid-testsuite/config
  aecid-testsuite/integration/aminerIntegrationTest2.sh
  aecid-testsuite/integration/declarations.sh
  aecid-testsuite/runCoverageTests.sh
  aecid-testsuite/runUnittests.sh
  scripts/aminerwrapper.sh
  scripts/supervisord.conf
Labels: enhancement
