Repository ait-aecid/logdata-anomaly-miner, pull requests merged in 2021-02, with the labels that each got.

#430 Improve output VCD
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableCorrelationDetector.py
Labels: enhancement

#436 Fixed the warning in the VCD
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableCorrelationDetector.py
Labels: bug

#437 Fixed the warning in the VTD
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py
Labels: bug

#438 Fixed VCD method match_disc_vals
  aecid-testsuite/unit/analysis/VariableCorrelationDetectorTest.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableCorrelationDetector.py
Labels: bug

#449 make wiki-tests branch-dependent
  Jenkinsfile
  aecid-testsuite/runGettingStarted.sh
  aecid-testsuite/runTryItOut.sh
Labels: bug, test

#455 Add documentation for params in ESD.
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventSequenceDetector.py
Labels: documentation

#457 011 fix pr template
  .github/pull_request_template.md
Labels: enhancement

#456 010 add kafka event handler to integration test2
  aecid-testsuite/integration/aminerIntegrationTest2.sh
  aecid-testsuite/integration/config22.py
  aecid-testsuite/integration/declarations.sh
Labels: test

#472 Fix: too many open directory-handles
  source/root/usr/lib/logdata-anomaly-miner/aminer/util/SecureOSFunctions.py
Labels: bug
