Repository ait-aecid/logdata-anomaly-miner, pull requests merged in 2021-07, with the labels that each got.

#790 Added the option to track on basis of the values of certain paths not only event types to the ETD
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventTypeDetector.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/AnalysisNormalisationSchema.yml
  source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
Labels: enhancement

#810 Fixed the falsely merged variable name
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/TSAArimaDetector.py
Labels: bug

#822 Feature docs
  README.md
  docs/CONFIGURATION.rst
  docs/conf.py
  docs/images/analysis-pipeline.png
Labels: documentation
