Repository ait-aecid/logdata-anomaly-miner, pull requests merged in 2021-01, with the labels that each got.

#393 Feature eventsequencedetector
  README.md
  aecid-testsuite/unit/analysis/EventSequenceDetectorTest.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlSchema.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventSequenceDetector.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/__init__.py
Labels: enhancement

#389 Added variables to the VCD
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlSchema.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableCorrelationDetector.py
Labels: enhancement

#397 Refactoring of the VTD-output
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py
Labels: enhancement, refactor

#400 Add frequency detector
  aecid-testsuite/unit/analysis/EventFrequencyDetectorTest.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlSchema.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventFrequencyDetector.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/__init__.py
Labels: enhancement

#391 Implemented the chisquare test
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlSchema.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableCorrelationDetector.py
Labels: enhancement

#405 Bugfix persistency warning
  .gitignore
  Dockerfile
  Jenkinsfile
  aecid-testsuite/Dockerfile
  aecid-testsuite/demo/AMiner/access.log
  aecid-testsuite/demo/AMiner/demo-config.py
  aecid-testsuite/demo/AMiner/demo-config.yml
  aecid-testsuite/runRemoteControlTest.sh
  aecid-testsuite/runSuspendModeTest.sh
  source/root/etc/aminer/template_config.yml
  source/root/usr/lib/logdata-anomaly-miner/aminer.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/AMinerConfig.py
  source/root/usr/lib/logdata-anomaly-miner/aminer/YamlSchema.py
Labels: bug

#413 Improve test documentation
  aecid-testsuite/unit/analysis/EventFrequencyDetectorTest.py
  aecid-testsuite/unit/analysis/EventSequenceDetectorTest.py
Labels: test
